# Generated by Django 3.2.25 on 2024-04-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_filmesdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
