# Generated by Django 3.2.25 on 2024-04-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_filmesdb', '0002_alter_filme_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='imagem',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXShDI6RpzKwxepFOA0j1nbEdqnLBZUO3CvYhiIVao4Hu_DPD5qW5PywfFAWf755Jvm54&usqp=CAU'),
        ),
        migrations.AddField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(default='Sinopse não disponível', max_length=500),
        ),
    ]
