# Generated by Django 3.2.25 on 2024-04-25 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_filmesdb', '0003_auto_20240424_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='comentario',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='filme',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
