# Generated by Django 3.2.25 on 2024-04-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_filmesdb', '0005_alter_filme_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='comentario',
            field=models.TextField(default='Sem comentários', max_length=500),
        ),
    ]
