# Generated by Django 3.2.25 on 2024-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_filmesdb', '0006_alter_filme_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='trailer_url',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
    ]
